version: "3.8"
services:
  db:
    image: postgres
    restart: always
    ports:
      -  "${DB_PORT}:5432"
    volumes:
      - "${DB_DATA_PATH}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"